// <auto-generated />
using System;
using GamAILab.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamAILab.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806115308_ModifiedAISimulationResponseModel")]
    partial class ModifiedAISimulationResponseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GamAILab.Shared.Models.AICodeEvaluation.AICodeTaskFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeTaskExecutionEvidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneationTimeInMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HintMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LLMModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskOutcome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodeSubmissionId")
                        .IsUnique();

                    b.ToTable("AICodeTaskFeedbacks");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AICodeEvaluation.AICodeTaskFeedbackDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeTaskExecutionEvidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneationTimeInMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HintMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LLMModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskOutcome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AICodeTaskFeedbackDTO");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIHallucinationChecker.HallucinationCheckResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AICodeTaskFeedbackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictedClaims")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GenerationTimeInMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LLMModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AICodeTaskFeedbackId");

                    b.ToTable("AIHallucinationCheckResults");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIPersonaSimulation.AIPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIPersonaSimulationResponseId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AccessibilityRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LearningCapabilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LearningDifficulties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIPersonaSimulationResponseId");

                    b.ToTable("AIPersonas");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIPersonaSimulation.AIPersonaSimulationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIPersonaSimulationResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeAttempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubmissionResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AIPersonaSimulationResponseId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SubmissionResultId");

                    b.ToTable("AIPersonaSimulationResult");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIPersonaSimulation.DTOs.AIPersonaSimulationResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeTaskTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeInMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AIPersonaSimulationResponses");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeExecution.CodeExecutionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DidComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EveryTestPassed")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ExecutionDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FatalError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CodeExecutionResult");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeExecution.CodeTestResult", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodeExecutionResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("passed");

                    b.HasKey("Key");

                    b.HasIndex("CodeExecutionResultId");

                    b.ToTable("CodeTestResult");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeSubmission.CodeSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodeSubmissions");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeSubmission.CodeSubmissionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AIFeedbackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ExecutionDuration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameProgressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HallucinationCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmittedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIFeedbackId");

                    b.HasIndex("CodeExecutionId");

                    b.HasIndex("CodeTaskId");

                    b.HasIndex("GameProgressId");

                    b.HasIndex("HallucinationCheckId");

                    b.ToTable("CodeSubmissionResult");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Examples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearnerGameProgressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LearnerGameProgressId");

                    b.ToTable("CodeTasks");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearnerGameProgressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearnerGameProgressId");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.CustomData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomData");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.DTOs.AchievementRequest", b =>
                {
                    b.Property<string>("AchievementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearnerGameProgressRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("AchievementId");

                    b.HasIndex("LearnerGameProgressRequestId");

                    b.ToTable("AchievementRequest");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.DTOs.LearnerGameProgressRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LearnerGameProgressRequest");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.GameObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameObjectives");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.LearnerGameProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearnerGameProgresses");
                });

            modelBuilder.Entity("GamAILab.WebApi.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AICodeEvaluation.AICodeTaskFeedback", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.CodeSubmission.CodeSubmission", "CodeSubmission")
                        .WithOne("AICodeTaskFeedback")
                        .HasForeignKey("GamAILab.Shared.Models.AICodeEvaluation.AICodeTaskFeedback", "CodeSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeSubmission");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIHallucinationChecker.HallucinationCheckResult", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.AICodeEvaluation.AICodeTaskFeedback", "AICodeTaskFeedback")
                        .WithMany()
                        .HasForeignKey("AICodeTaskFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AICodeTaskFeedback");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIPersonaSimulation.AIPersona", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.AIPersonaSimulation.DTOs.AIPersonaSimulationResponse", null)
                        .WithMany("PersonasUsed")
                        .HasForeignKey("AIPersonaSimulationResponseId");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIPersonaSimulation.AIPersonaSimulationResult", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.AIPersonaSimulation.DTOs.AIPersonaSimulationResponse", null)
                        .WithMany("PersonaResults")
                        .HasForeignKey("AIPersonaSimulationResponseId");

                    b.HasOne("GamAILab.Shared.Models.AIPersonaSimulation.AIPersona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamAILab.Shared.Models.CodeSubmission.CodeSubmissionResult", "SubmissionResult")
                        .WithMany()
                        .HasForeignKey("SubmissionResultId");

                    b.Navigation("Persona");

                    b.Navigation("SubmissionResult");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeExecution.CodeTestResult", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.CodeExecution.CodeExecutionResult", null)
                        .WithMany("CodeTests")
                        .HasForeignKey("CodeExecutionResultId");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeSubmission.CodeSubmissionResult", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.AICodeEvaluation.AICodeTaskFeedbackDTO", "AIFeedback")
                        .WithMany()
                        .HasForeignKey("AIFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamAILab.Shared.Models.CodeExecution.CodeExecutionResult", "CodeExecution")
                        .WithMany()
                        .HasForeignKey("CodeExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamAILab.Shared.Models.CodeTask", "CodeTask")
                        .WithMany()
                        .HasForeignKey("CodeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamAILab.Shared.Models.Game.DTOs.LearnerGameProgressRequest", "GameProgress")
                        .WithMany()
                        .HasForeignKey("GameProgressId");

                    b.HasOne("GamAILab.Shared.Models.AIHallucinationChecker.HallucinationCheckResult", "HallucinationCheck")
                        .WithMany()
                        .HasForeignKey("HallucinationCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIFeedback");

                    b.Navigation("CodeExecution");

                    b.Navigation("CodeTask");

                    b.Navigation("GameProgress");

                    b.Navigation("HallucinationCheck");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeTask", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.Game.LearnerGameProgress", null)
                        .WithMany("CompletedTasks")
                        .HasForeignKey("LearnerGameProgressId");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.Achievement", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.Game.LearnerGameProgress", null)
                        .WithMany("Achievements")
                        .HasForeignKey("LearnerGameProgressId");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.DTOs.AchievementRequest", b =>
                {
                    b.HasOne("GamAILab.Shared.Models.Game.DTOs.LearnerGameProgressRequest", null)
                        .WithMany("Achievements")
                        .HasForeignKey("LearnerGameProgressRequestId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GamAILab.WebApi.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GamAILab.WebApi.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamAILab.WebApi.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GamAILab.WebApi.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamAILab.Shared.Models.AIPersonaSimulation.DTOs.AIPersonaSimulationResponse", b =>
                {
                    b.Navigation("PersonaResults");

                    b.Navigation("PersonasUsed");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeExecution.CodeExecutionResult", b =>
                {
                    b.Navigation("CodeTests");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.CodeSubmission.CodeSubmission", b =>
                {
                    b.Navigation("AICodeTaskFeedback");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.DTOs.LearnerGameProgressRequest", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("GamAILab.Shared.Models.Game.LearnerGameProgress", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("CompletedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
