version: '3.8'

services:
  gamai-lab-webapi:
    image: gamai-lab-webapi
    build:
      context: .
      dockerfile: gamai-lab-webapi/Dockerfile
    ports: 
    - "5270:8080"
    volumes:
      - gamai_lab_data:/app/data
    environment:
        ASPNETCORE_URLS: http://+:8080
        ASPNETCORE_ENVIRONMENT: Development

  gamailab.frontend:
    image: gamailab.frontend
    build:
      context: .
      dockerfile: GamAILab.Frontend/Dockerfile
    ports: 
    - "5123:8080"
    volumes:
      - gamai_lab_data:/app/data
    environment:
        ASPNETCORE_URLS: http://+:8080
        ASPNETCORE_ENVIRONMENT: Development
        
volumes:
  gamai_lab_data:

