services:
  gamai-lab-webapi:
    image: gamai-lab-webapi
    build:
      context: .
      dockerfile: gamai-lab-webapi/Dockerfile

  gamailab.frontend:
    image: gamailab.frontend
    build:
      context: .
      dockerfile: GamAILab.Frontend/Dockerfile

